{'noticeInfo': {'additionalContactInfo': None,
                'additionalPricesMatchingDate': None,
                'applExaminationTime': None,
                'applSubmisionPlace': 'Электронная площадка РТС-тендер '
                                      '(http://www.rts-tender.ru)',
                'applSubmisionStartDate': 1606683600000,
                'applSubmissionCloseTime': 1608800400000,
                'auctionTime': None,
                'considerationSecondPartDate': None,
                'contractorAgencyType': 0,
                'customerFullAddress': '629008, АО ЯМАЛО-НЕНЕЦКИЙ,Г '
                                       'САЛЕХАРД,УЛ РЕСПУБЛИКИ, дом ДОМ 73, '
                                       'офис (квартира) КОМНАТА 100',
                'customerInn': '7720261827',
                'customerKpp': '890101001',
                'customerName': 'ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО '
                                '"ГОСУДАРСТВЕННАЯ ТРАНСПОРТНАЯ ЛИЗИНГОВАЯ '
                                'КОМПАНИЯ"',
                'customerOgrn': '1027739407189',
                'customerPostalAddress': '125284, Москва, Ленинградский, дом '
                                         '37, корпус 1',
                'email': 'Sudenko.VY@gtlk.ru',
                'envelopeOpeningTime': None,
                'fax': None,
                'firstName': 'В.',
                'id': 12052523,
                'lastName': 'Суденко',
                'lots': [{'centralized': False,
                          'commoditiesWorkServiceses': [{'additionalInfo': None,
                                                         'amountOfCommodities': 1,
                                                         'deliveryPlace': None,
                                                         'id': 31497806,
                                                         'impossibleToDetermineAttr': False,
                                                         'okei': {'actual': True,
                                                                  'charCode': 'ЕД',
                                                                  'digitalCode': '642',
                                                                  'id': 202355,
                                                                  'internationCharCode': None,
                                                                  'internationName': None,
                                                                  'localName': 'ед',
                                                                  'name': 'Единица'},
                                                         'okpd2': {'code': '30.11.21.114',
                                                                   'id': 8888502,
                                                                   'name': 'Паромы '
                                                                           'пассажирские '
                                                                           'морские'},
                                                         'okved2': {'code': '30.11',
                                                                    'id': 8830232,
                                                                    'name': 'Строительство '
                                                                            'кораблей, '
                                                                            'судов '
                                                                            'и '
                                                                            'плавучих '
                                                                            'конструкций',
                                                                    'section': 'C'},
                                                         'orderNumber': 1}],
                          'commodityPrice': None,
                          'commodityPriceRub': None,
                          'contractSubject': 'Самоходный '
                                             'автомобильно-пассажирский паром',
                          'currency': {'actual': True,
                                       'code': 'RUB',
                                       'dateutv': None,
                                       'digitalCode': '643',
                                       'endtActiveDate': 1303489510000,
                                       'id': 1,
                                       'lastModifyDate': 1365422030000,
                                       'name': 'Российский рубль',
                                       'shortName': 'Россия',
                                       'startActiveDate': 1303489510000},
                          'deliveryPlace': {'address': 'Крым Респ , ОКАТО: '
                                                       '35000000000',
                                            'regionId': 8248959},
                          'deliveryPlaceIndication': 'GL',
                          'exchangeRate': None,
                          'exchangeRateDate': None,
                          'id': 13408641,
                          'impossibleToDeterminePrice': False,
                          'inputTypeNMSK': 'NMSK',
                          'jointLot': False,
                          'lotApplications': [],
                          'lotCriterias': [],
                          'lotCustomers': [],
                          'lotToLotCancellations': [],
                          'lotToProtocolAllocations': [],
                          'ordinalNumber': 1,
                          'planId': 547933,
                          'planInfoId': 4579695,
                          'planPositionId': 76579774756,
                          'planType': 'COMMODITY',
                          'priceInformation': None,
                          'reestrNumber': '2190396235',
                          'startingContractPrice': 255000000,
                          'startingContractPriceRub': 255000000}],
                'patronymic': 'Ю.',
                'phone': '+749 (522) 100121352',
                'purchaseName': 'Самоходный автомобильно-пассажирский паром',
                'quotationExaminationTime': None,
                'summingupTime': 1609243200000,
                'urlVsrz': 'https://223.rts-tender.ru/supplier/auction/Trade/View.aspx?Id=1931098'},
 'purchase': {'contracts': [], 'customerId': 3344, 'id': 10042619},
 'purchaseMethod': {'changeable': True,
                    'competitive': True,
                    'digitalPurchase': True,
                    'extended': False,
                    'hasPhases': False,
                    'hasPurchases': 'P',
                    'id': 296182,
                    'methodType': 'IS',
                    'name': 'Открытый конкурс',
                    'status': 'RELEVANT',
                    'typal': True,
                    'typalKind': 'TSK'},
 'timeZones': [{'actual': True,
                'ahead': False,
                'id': 12,
                'name': 'МСК-1 (СГВ+2) Калининград',
                'offset': -1,
                'shortName': 'МСК-1'},
               {'actual': True,
                'ahead': False,
                'id': 13,
                'name': 'МСК (СГВ+3) Москва',
                'offset': 0,
                'shortName': 'МСК'},
               {'actual': True,
                'ahead': True,
                'id': 14,
                'name': 'МСК+1 (СГВ+4) Волгоград, Самара',
                'offset': 1,
                'shortName': 'МСК+1'},
               {'actual': True,
                'ahead': True,
                'id': 15,
                'name': 'МСК+2 (СГВ+5) Екатеринбург, Челябинск, Уфа',
                'offset': 2,
                'shortName': 'МСК+2'},
               {'actual': True,
                'ahead': True,
                'id': 16,
                'name': 'МСК+3 (СГВ+6) Новосибирск, Омск',
                'offset': 3,
                'shortName': 'МСК+3'},
               {'actual': True,
                'ahead': True,
                'id': 17,
                'name': 'МСК+4 (СГВ+7) Красноярск',
                'offset': 4,
                'shortName': 'МСК+4'},
               {'actual': True,
                'ahead': True,
                'id': 18,
                'name': 'МСК+5 (СГВ+8) Иркутск',
                'offset': 5,
                'shortName': 'МСК+5'},
               {'actual': True,
                'ahead': True,
                'id': 19,
                'name': 'МСК+6 (СГВ+9) Якутск',
                'offset': 6,
                'shortName': 'МСК+6'},
               {'actual': True,
                'ahead': True,
                'id': 20,
                'name': 'МСК+7 (СГВ+10) Владивосток, Хабаровск',
                'offset': 7,
                'shortName': 'МСК+7'},
               {'actual': True,
                'ahead': True,
                'id': 21,
                'name': 'МСК+8 (СГВ+11) Среднеколымск',
                'offset': 8,
                'shortName': 'МСК+8'},
               {'actual': True,
                'ahead': True,
                'id': 22,
                'name': 'МСК+9 (СГВ+12) Петропавловск-Камчатский',
                'offset': 9,
                'shortName': 'МСК+9'}]}
[Finished in 0.5s]